version: "3.4"

x-common-variables: &common-variables
  MYSQL_HOST: "${MYSQL_HOST}"
  MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  MYSQL_DATABASE: "${MYSQL_ROOT_PASSWORD}"

services:
  mysql-db:
    build: .
    image: mysql
    container_name: mysql_container
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    environment:
      <<: *common-variables
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    restart: unless-stopped
    volumes:
      - "./db.sql:/docker-entrypoint-initdb.d/db.sql"
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin
    container_name:  phpmyadmin_container
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always