version: "3.4"

services:
  redis:
    image: redis
    container_name: redis_container
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ./data:/data
    restart: always